# Generated by Django 2.1.1 on 2018-10-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Comuna'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nomComuna',
            field=models.CharField(max_length=100, verbose_name='Comuna'),
        ),
    ]
