# Generated by Django 2.1.1 on 2018-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181024_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Vivienda',
            new_name='TipoVivienda',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
